# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-21 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_hash',
            field=models.CharField(default='none', max_length=255),
            preserve_default=False,
        ),
    ]
